global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: postgres-exporter-users
    static_configs:
      - targets: ["192.168.0.168:9187"]
  - job_name: api-gateway
    static_configs:
      - targets: ['192.168.0.168:8080']
  - job_name: posgres-exporter-tasks
    static_configs:
      - targets: ['192.168.0.168:9188']
